---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! Tower is working!"
    
  - name: install the latest version of Apache from the testing repo
    yum:
      name: httpd
      state: present
  
  - service:
      name: httpd
      state: started
